IBX-6804 - VAT rate assignment in product type
ibexa/documentation-user pull request #232
Opened 2023-10-13 13:11 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | [IBX-6804](https://issues.ibexa.co/browse/IBX-6804) |
| Versions      | master |
| Edition       | all |

Document the updated VAT assignment procedure and accompanying changes.

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale
- [x] Description metadata is up to date
- [x] Added link to this PR in relevant JIRA ticket or code PR

2023-10-13 13:39 UTC, konradoboza approved these changes

2023-10-16 05:48 UTC, julitafalcondusza approved these changes

2023-10-16 06:41 UTC, juskora approved these changes

2023-10-16 06:41 UTC, juskora commented on docs/pim/create_product_types.md
> +    When your website supports a large number of regions, the search field helps you find the right region.
```suggestion
    When your website supports a large number of regions, use the search field to find the right region.
```

2023-10-16 07:40 UTC, MagdalenaZuba requested changes

2023-10-16 07:40 UTC, MagdalenaZuba commented on docs/pim/create_product_types.md
> +    When your website supports a large number of regions, use the search field to find the right region.
```suggestion
    When your website supports multiple regions, use the search field to find the right one.
```

2023-10-16 07:40 UTC, MagdalenaZuba commented on docs/pim/img/vat_rates_product_type.png
This screenshot is blurry.

2023-10-16 07:40 UTC, MagdalenaZuba commented on docs/pim/products.md
> +A product type also defines the attributes that all products of this type can have, as well as VAT rates that apply to all products of this type.
```suggestion
A product type also defines both the attributes and VAT rates for all its products.
```

2023-10-16 09:55 UTC, MagdalenaZuba approved these changes

2023-10-16 10:24 UTC, merged