Added SeenThis page block and custom tag
ibexa/documentation-user pull request #236
Opened 2023-10-20 12:57 UTC by juskora

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      | master, 4.6
| Edition       | all

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-10-31 07:40 UTC, adamwojs commented on docs/content_management/block_reference.md
> +SeenThis! block provides an adaptive streaming technology with no limitations as conventional streaming service. It allows to preserve the best video quality with minimum amount of data transfer.
```suggestion
Integration with (SeenThis!)[https://seenthis.co/] service. SeenThis! block provides an adaptive streaming technology with no limitations as conventional streaming service. It allows to preserve the best video quality with minimum amount of data transfer.
```

2023-10-31 07:40 UTC, adamwojs commented on docs/content_management/block_reference.md
> +    This page block is in an opt-in bundle, to use it, install the bundle first.
```suggestion
    This page block is in an opt-in bundle, to use it, install `ibexa/connector-seenthis` bundle first.
```

2023-10-31 07:40 UTC, adamwojs commented on docs/content_management/create_edit_content_items.md
> +    This custom tag is in an opt-in bundle, to use it, install the bundle first.
```suggestion
    This custom tag is in an opt-in bundle, to use it, install `ibexa/connector-seenthis` bundle first.
```

2023-10-31 13:09 UTC, dabrt requested changes

2023-10-31 13:09 UTC, dabrt commented on docs/content_management/block_reference.md
> +On the **Design** tab, in the **View** field, select the layout to be used to present a list of products and submit your changes.
```suggestion
On the **Design** tab, in the **View** field, select the layout to be used to present a list of products, and submit your changes.
```

2023-10-31 13:09 UTC, dabrt commented on docs/content_management/block_reference.md
> +    SeenThis technology might be blocked by some ad blocker solutions. If you can't see the block once configured, check ad blocker configuration.
```suggestion
    Some ad blocker solutions block content that comes from SeenThis. If you can't see the block after it is configured, check the ad blocker configuration.
```

2023-10-31 13:44 UTC, juskora commented on docs/content_management/create_edit_content_items.md
> +    This custom tag is in an opt-in bundle, to use it, install `ibexa/connector-seenthis` bundle first.
It's a bundle.

2023-10-31 14:12 UTC, MagdalenaZuba requested changes

2023-10-31 14:12 UTC, MagdalenaZuba commented on docs/content_management/block_reference.md
> +Integration with (SeenThis!)[https://seenthis.co/] service. SeenThis! block provides an adaptive streaming technology with no limitations as conventional streaming service. It allows to preserve the
We discussed it as a team last week, we even have a ticket for it https://issues.ibexa.co/browse/IBX-6762, but it is not in Justyna's scope so let's not dwell on that 😃

2023-10-31 14:12 UTC, MagdalenaZuba commented on docs/content_management/block_reference.md
> +    SeenThis technology might be blocked by some ad blocker solutions. If you can't see the block once configured, check ad blocker configuration.
```suggestion
    SeenThis! technology might be blocked by some ad blocker solutions. If you can't see the block once configured, check the ad blocker configuration.
```

2023-10-31 14:12 UTC, MagdalenaZuba commented on docs/content_management/block_reference.md
> +- **Include audio** – Set to include or not audio with the video.
```suggestion
- **Include audio** – Configure whether to include audio with the video.
```

2023-10-31 14:12 UTC, MagdalenaZuba commented on docs/content_management/block_reference.md
> +- **Loop** – Set to play a video in a loop mode.
```suggestion
- **Loop** – Set whether to play a video in a loop mode.
```

2023-11-06 10:04 UTC, MagdalenaZuba approved these changes

2023-11-06 13:40 UTC, julitafalcondusza approved these changes

2023-11-06 14:04 UTC, adamwojs approved these changes

2023-11-06 14:04 UTC, merged