IBX-6709: Page Builder amendments
ibexa/documentation-user pull request #239
Opened 2023-10-27 10:59 UTC by julitafalcondusza

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | (https://issues.ibexa.co/browse/IBX-6709)
| Versions      | master
| Edition       | Experience, Commerce

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2024-01-05 13:11 UTC, dkorostynski approved these changes

2024-01-08 10:20 UTC, Gengar-i requested changes

2024-01-08 10:20 UTC, Gengar-i commented on docs/content_management/create_edit_pages.md
> +D. Mode toolbar (including Desktop, Tablet and Mobile mode)
Maybe Device toolbar?

2024-01-08 12:59 UTC, julitafalcondusza commented on docs/content_management/create_edit_pages.md
> +**Page** is a special Content Type.
Not in the scope of this PR, will be covered in separated PR.

2024-01-08 12:59 UTC, julitafalcondusza commented on docs/content_management/create_edit_pages.md
> +    The Page Content Type contains a **Landing Page** Field Type which manages
Not in the scope of this PR, will be covered in separated PR.

2024-01-09 09:52 UTC, dew326 approved these changes

2024-01-09 10:51 UTC, Gengar-i approved these changes

2024-01-09 11:15 UTC, dabrt reviewed
Make sure you merge in changes from previous PRs and add your changes again.

2024-01-09 11:15 UTC, dabrt commented on docs/content_management/create_edit_pages.md
> +You can create and modify Pages with a visual drag-and-drop editor - Page Builder.
```suggestion
You can create and modify Pages with a visual drag-and-drop editor, the Page Builder.
```

2024-01-09 11:15 UTC, dabrt commented on docs/content_management/create_edit_pages.md
> +By editing pages you can customize the layout and content of your website.
```suggestion
Pages are divided into zones into which you can drop various dynamic blocks.
By editing pages, you can customize the layout and content of your website.
```

2024-01-09 14:56 UTC, closed without merging